{{- $file := .Values.auth.importFileLocation }}
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: realm-import
data:
  realmimport.json: |-
    {{- tpl ($.Files.Get $file) . | nindent 4 }}
